[build]
  command = "npm run build"
  functions = "functions/"
  publish = "public/"

[dev]
  publish = "public/"
  port = 1234

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/.netlify/functions/api"
    [headers.values]
    Access-Control-Allow-Origin = "*"