[build]
  command = "npm run build"
  functions = "functions/"
  publish = "public/"

[dev]
  command = "npm run dev"
  functionsPort = 34567
  functions = "functions/"
  publish = "public"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/.netlify/functions/api"
    [headers.values]
    Access-Control-Allow-Origin = "*"